### ISSUE TITLE
Force use of cross instead of cargo?

### ISSUE THREAD

**Issue by rotivleal** [houseabsolute/actions-rust-cross#14]
Is there an option to make it always use `cross`? 

I am trying to compile to `x86_64_unknown_linux_musl` but my build fails because it is missing the `musl-gcc` and some other libs necessary to cross-compile with MUSL.

**Comment by autarch** [comment]
There's no such option right now. It wouldn't be hard to add but in this case why not just install the necessary packages as part of your workflow?

**Comment by autarch** [comment]
I realized that this is actually the same as #20, which is fixed in v0.0.14.
