### ISSUE TITLE
Is cross test still unsupported for windows-arm and mac-os arm?

### ISSUE THREAD

**Issue by lilith** [houseabsolute/actions-rust-cross#19]
In readme: `test command will fail with *BSD targets, non-x86 Windows, and macOS ARM.`

I believe these are now supported by cross and cargo; is that the only underlying issue for those platforms or is there something specific to this action?

**Comment by autarch** [comment]
Just to clarify, this project _does not_ use `cross` on macOS or Windows, because `cargo` seems to work out of the box. I just tested and it seems like `cargo test` now works on those platforms as well, so I'll update the README. Thanks for asking about this!

**Comment by autarch** [comment]
Actually, I take it back. It seems like `cargo test` works fine macOS ARM now, but it still doesn't work on Windows. That makes sense, since I wouldn't expect an ARM binary to be executable on Windows x86 machines.
