### ISSUE TITLE
feature request: DinD

### ISSUE THREAD

**Issue by ilteoood** [houseabsolute/actions-rust-cross#21]
My application has some tests that relies on docker to work.
When I run them on a platform that requires cross, Docker is not accessible.
It would be amazing to have docker support by default, as described in the [cross documentation](https://github.com/cross-rs/cross?tab=readme-ov-file#docker-in-docker)

**Comment by autarch** [comment]
It's not clear to me from that link what exactly I would need to do in this action to enable this. The docs talk about _installing `cross`_ inside a container to enable this. But all that this action does is download a `cross` binary and run that for you.

**Comment by ilteoood** [comment]
My bad. I thought it required additional info in order to mount the docker sock.
At the end, I saw we can use the `CROSS_CONTAINER_OPTS` env variable to do that.
