### ISSUE TITLE
Specifying a toolchain with a date `nightly-2023-09-30` and a `rust-toolchain.toml`

### ISSUE THREAD

**Issue by tombh** [houseabsolute/actions-rust-cross#27]
Here's the error, note that it is for `aarch64-unknown-linux-gnu` even though the generated toolchain name is for `x86_64-unknown-linux-gnu`:
```
Run /home/runner/work/_temp/cross +nightly-2023-09-30 build --locked --release --target aarch64-unknown-linux-gnu
error: error: invalid value 'nightly-2023-09-30-2023-09-30-x86_64-unknown-linux-gnu' for '<toolchain>...': invalid toolchain name: 'nightly-2023-09-30-2023-09-30-x86_64-unknown-linux-gnu'
```
Full logs: https://github.com/tombh/rust-gpu-cli/actions/runs/11317667123/job/31471379599#step:4:714

It looks like `cross` honours `rust-toolchain.toml` and correctly provides the toolchain date (though the incorrect target). Whereas `cargo` requires setting the full `nightly-2023-09-30` in the action's `toolchain` field.

I'm happy to look into this myself, just wondering if anybody has any insights?

**Comment by tombh** [comment]
Looks like this is a known issue in `cross`: https://github.com/cross-rs/cross/issues/1541

**Comment by autarch** [comment]
I'm going to close this since it's a cross issue. Hopefully they'll do a release some time soon.
