### ISSUE TITLE
Would love to be able to run this in a subdirectory in a monorepo

### ISSUE THREAD

**Issue by aaronvg** [houseabsolute/actions-rust-cross#6]
Unfortunately this fails on monorepos since one can't set the working directory of actions.

Appreciate the tutorial you wrote!

**Comment by aaronvg** [comment]
https://github.com/houseabsolute/actions-rust-cross/pull/7

**Comment by autarch** [comment]
I just released v0.0.9 which implements this. I called the parameter `working-directory` since that's what GH Actions calls it for its own commands. Thanks!
